'use strict';
/**
 * One-off build script: downloads the latin subsets of the two brand typefaces
 * and self-hosts them in public/fonts so the site makes ZERO third-party
 * requests at runtime. Committed output: public/fonts/*.woff2 + fonts.css
 *
 *   • Plus Jakarta Sans  — body copy, UI, navigation
 *   • Poppins            — display headings, section titles, buttons
 *
 * Run once: node scripts/fetch-fonts.js
 */

const fs = require('fs');
const path = require('path');

const OUT = path.resolve(__dirname, '..', 'public', 'fonts');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  {
    css: 'Plus+Jakarta+Sans',
    label: 'Plus Jakarta Sans',
    file: 'plus-jakarta-sans',
    weights: [400, 500, 600, 700, 800],
    style: 'normal'
  },
  {
    css: 'Poppins',
    label: 'Poppins',
    file: 'poppins',
    weights: [500, 600, 700],
    style: 'normal'
  }
];

async function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const rules = [];
  let count = 0;

  for (const fam of FAMILIES) {
    for (const w of fam.weights) {
      const url = `https://fonts.googleapis.com/css2?family=${fam.css}:wght@${w}&display=swap`;
      const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

      // Each subset is written as:  /* subset-name */  @font-face { ... }
      // Parse the pairs directly — the comment belongs to the block that follows.
      const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
      let latin = null;
      let m;
      while ((m = re.exec(css))) {
        if (m[1] === 'latin') latin = m[2];
      }
      if (!latin) {
        console.warn(`  ! no latin subset for ${fam.label} ${w}`);
        continue;
      }
      const urlMatch = latin.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      if (!urlMatch) {
        console.warn(`  ! no woff2 url for ${fam.label} ${w}`);
        continue;
      }
      const range = (latin.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';

      const buf = Buffer.from(await (await fetch(urlMatch[1], { headers: { 'User-Agent': UA } })).arrayBuffer());
      const file = `${fam.file}-${w}.woff2`;
      fs.writeFileSync(path.join(OUT, file), buf);
      console.log(`  \u2713 ${file}  ${(buf.length / 1024).toFixed(1)} KB`);
      count++;

      rules.push(
        `@font-face{font-family:'${fam.label}';font-style:${fam.style};font-weight:${w};font-display:swap;` +
          `src:url('/fonts/${file}') format('woff2');` +
          (range ? `unicode-range:${range.trim()};` : '') +
          `}`
      );
    }
  }

  fs.writeFileSync(
    path.join(OUT, 'fonts.css'),
    `/* Self-hosted \u2014 generated by scripts/fetch-fonts.js. Do not edit by hand. */\n` +
      rules.join('\n') +
      '\n'
  );
  console.log(`\nWrote ${rules.length} @font-face rules (${count} files) to public/fonts/fonts.css`);
}

main().catch((e) => {
  console.error('Font fetch failed:', e.message);
  process.exitCode = 1;
});
